### ISSUE TITLE
KeyError: '' when running `get_scans()`

### ISSUE THREAD

**Issue by nitrocode** [rapid7/vm-console-client-python#17]
I cloned this repo and created the following file with environment variables ADUSERNAME and ADPASSWORD. The exception is shown below.

`test.py`
```
from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint
import base64
import os

config = swagger_client.Configuration(name='Rapid7')
config.username = os.environ['ADUSERNAME']
config.password = os.environ['ADPASSWORD']
config.host = 'https://insightsvm.mycompany.com'
config.verify_ssl = True
config.assert_hostname = False
config.proxy = None
config.ssl_ca_cert = None
config.connection_pool_maxsize = None
config.cert_file = None
config.key_file = None
# config.safe_chars_for_path_param = ''

auth = "%s:%s" % (config.username, config.password)
auth = base64.b64encode(auth.encode('ascii')).decode()
client = swagger_client.ApiClient(configuration=config)
client.default_headers['Authorization'] = "Basic %s" % auth

# create an instance of the API class
active = False # bool | Return running scans or past scans (true/false value). (optional) (default to false)
page = 0 # int | The index of the page (zero-based) to retrieve. (optional) (default to 0)
size = 10 # int | The number of records per page to retrieve. (optional) (default to 10)
sort = ['sort_example'] # list[str] | The criteria to sort the records by, in the format: `property[,ASC|DESC]`. The default sort order is ascending. Multiple sort criteria can be specified using multiple sort query parameters. (optional)

scan_client = swagger_client.ScanApi(client)
json = scan_client.get_scans(active=active, page=page, size=size, sort=sort)
pprint(json)
```

Upon the `get_scans` function, it returns the following exception.

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    json = scan_client.get_scans(active=active, page=page, size=size, sort=sort)
  File "/Users/user/git/github/insightvm/swagger_client/api/scan_api.py", line 157, in get_scans
    (data) = self.get_scans_with_http_info(**kwargs)  # noqa: E501
  File "/Users/user/git/github/insightvm/swagger_client/api/scan_api.py", line 241, in get_scans_with_http_info
    collection_formats=collection_formats)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 322, in call_api
    _preload_content, _request_timeout)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 233, in deserialize
    return self.__deserialize(data, response_type)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 250, in __deserialize
    for sub_data in data]
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 250, in __deserialize
    for sub_data in data]
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/user/git/github/insightvm/swagger_client/api_client.py", line 624, in __deserialize_model
    klass_name = instance.get_real_child_model(data)
  File "/Users/user/git/github/insightvm/swagger_client/models/link.py", line 107, in get_real_child_model
    discriminator_value = data[self.discriminator].lower()
KeyError: ''
```

**Comment by nitrocode** [comment]
This is an error in the swagger code generator. I was able to work around this by putting a try catch around https://github.com/rapid7/vm-console-client-python/blob/master/rapid7vmconsole/api_client.py#L622-L624
