### ISSUE TITLE
Package not being recognized by Python

### ISSUE THREAD

**Issue by gzigg** [rapid7/vm-console-client-python#27]
## Issues and Contributing
Python does not seem to recognize the "rapid7-vm-console" package, despite PIP showing it is installed.   The issue seems related to the dashes in the name (see output pasted below).   So what package name should be used in scripts?   It seems that using  dashes in the package name  induces other errors (I think the dash is seen as a minus sign).  

### Expected Behavior
The scripts should be able to import the package, but the script dies at that point since rapid7-vm-console cannot be imported. 

### Actual Behavior
Here is the output whenever a sample script is attempted, followed by PIP list confirming the package is indeed installed, but no matter what it is not recognized:

-----------SAMPLE SCRIPT FAILS----------------------------------

        [user@RHEL_77_server rapid7]$ ./list_assets.py
          File "./list_assets.py", line 3
            import rapid7-vm-console
                         ^
        SyntaxError: invalid syntax

------------PIP Output & Attempted Import on CLI ------------------

	[user@RHEL_77_server rapid7]$
	[user@RHEL_77_server rapid7]$ pip list | grep rapid7
	rapid7-vm-console                1.0.0-6.5.50
	[user@RHEL_77_server rapid7]$
	[user@RHEL_77_server rapid7]$
	[user@RHEL_77_server rapid7]$
	[user@RHEL_77_server rapid7]$
	[user@RHEL_77_server rapid7]$ python
	Python 2.7.5 (default, Jun 11 2019, 14:33:56)
	[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>>
	>>>
	>>> import rapid7vmconsole       <--TESTING THIS PACKAGE NAME (sans dashes)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	**ImportError: No module named rapid7vmconsole**
	>>>
	>>>
	>>> import rapid7-vm-console      <--THIS IS THE CORRECT PACKAGE NAME (with dashes)
	  File "<stdin>", line 1
		import rapid7-vm-console
					 ^
	**SyntaxError: invalid syntax**
	>>>
	>>>
	>>> import rapid7_vm_console           <--TESTING THIS PACKAGE NAME(with underscores)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	**ImportError: No module named rapid7_vm_console**
	>>>
	>>>
	>>>

### Possible Solution
Are the dashes a problem for this package, or how to get Python to actually import the package to use in scripts?  Thanks.

### Steps to Reproduce (for bugs)
BTW, I followed all the package/module installation steps outlined in the README doc here:
https://github.com/rapid7/vm-console-client-python/blob/master/README.md#installation--usage

And here is the output from those steps:

		[user@RHEL_77_server rapid7]$
		[user@RHEL_77_server rapid7]$ sudo pip install git+https://github.com/rapid7/vm-console-client-pyth
		on.git
		Collecting git+https://github.com/rapid7/vm-console-client-python.git
		  Cloning https://github.com/rapid7/vm-console-client-python.git to /tmp/pip-req-build-QKna6s
		  Running command git clone -q https://github.com/rapid7/vm-console-client-python.git /tmp/pip-req-b
		uild-QKna6s
		Requirement already satisfied (use --upgrade to upgrade): rapid7-vm-console===1.0.0-6.5.50 from git+
		https://github.com/rapid7/vm-console-client-python.git in /root/.local/lib/python2.7/site-packages/r
		apid7_vm_console-1.0.0_6.5.50-py2.7.egg
		Requirement already satisfied: urllib3>=1.15 in /usr/lib/python2.7/site-packages (from rapid7-vm-con
		sole===1.0.0-6.5.50) (1.25.8)
		Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from rapid7-vm-console
		===1.0.0-6.5.50) (1.14.0)
		Requirement already satisfied: certifi in /usr/lib/python2.7/site-packages (from rapid7-vm-console==
		=1.0.0-6.5.50) (2019.11.28)
		Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from rapid7-vm-c
		onsole===1.0.0-6.5.50) (2.8.1)
		[user@RHEL_77_server rapid7]$
		[user@RHEL_77_server rapid7]$
		[user@RHEL_77_server rapid7]$
		[user@RHEL_77_server rapid7]$
		[user@RHEL_77_server rapid7]$ sudo python ./setup.py install --user
		/usr/lib/python2.7/site-packages/setuptools/dist.py:485: UserWarning: The version specified ('1.0.0-
		6.5.50') is an invalid version, this may not work as expected with newer versions of setuptools, pip
		, and PyPI. Please see PEP 440 for more details.
		  "details." % self.metadata.version
		running install
		running bdist_egg
		running egg_info
		writing requirements to rapid7_vm_console.egg-info/requires.txt
		writing rapid7_vm_console.egg-info/PKG-INFO
		writing top-level names to rapid7_vm_console.egg-info/top_level.txt
		writing dependency_links to rapid7_vm_console.egg-info/dependency_links.txt
		reading manifest file 'rapid7_vm_console.egg-info/SOURCES.txt'
		writing manifest file 'rapid7_vm_console.egg-info/SOURCES.txt'
		installing library code to build/bdist.linux-x86_64/egg
		running install_lib
		warning: install_lib: 'build/lib' does not exist -- no Python modules to install

		creating build/bdist.linux-x86_64/egg
		creating build/bdist.linux-x86_64/egg/EGG-INFO
		copying rapid7_vm_console.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
		copying rapid7_vm_console.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
		copying rapid7_vm_console.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
		copying rapid7_vm_console.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
		copying rapid7_vm_console.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
		zip_safe flag not set; analyzing archive contents...
		creating 'dist/rapid7_vm_console-1.0.0_6.5.50-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' t
		o it
		removing 'build/bdist.linux-x86_64/egg' (and everything under it)
		Processing rapid7_vm_console-1.0.0_6.5.50-py2.7.egg
		Removing /root/.local/lib/python2.7/site-packages/rapid7_vm_console-1.0.0_6.5.50-py2.7.egg
		Copying rapid7_vm_console-1.0.0_6.5.50-py2.7.egg to /root/.local/lib/python2.7/site-packages
		rapid7-vm-console 1.0.0-6.5.50 is already the active version in easy-install.pth

		Installed /root/.local/lib/python2.7/site-packages/rapid7_vm_console-1.0.0_6.5.50-py2.7.egg
		Processing dependencies for rapid7-vm-console===1.0.0-6.5.50
		Searching for python-dateutil==2.8.1
		Best match: python-dateutil 2.8.1
		Adding python-dateutil 2.8.1 to easy-install.pth file

		Using /usr/lib/python2.7/site-packages
		Searching for certifi==2019.11.28
		Best match: certifi 2019.11.28
		Adding certifi 2019.11.28 to easy-install.pth file

		Using /usr/lib/python2.7/site-packages
		Searching for six==1.14.0
		Best match: six 1.14.0
		Adding six 1.14.0 to easy-install.pth file

		Using /usr/lib/python2.7/site-packages
		Searching for urllib3==1.25.8
		Best match: urllib3 1.25.8
		Adding urllib3 1.25.8 to easy-install.pth file

		Using /usr/lib/python2.7/site-packages
		Finished processing dependencies for rapid7-vm-console===1.0.0-6.5.50
		[user@RHEL_77_server rapid7]$ 

### Your Environment
* Library version or repository branch:   rapid7-vm-console                1.0.0-6.5.50
* Python version:   2.7.5
* Operating System and version:   Red Hat Enterprise Linux Server release 7.7 (Maipo)
* InsightVM/Nexpose product version:   Nexpose latest version

**Comment by gzigg** [comment]
This appears to have been resolved it by re-running the pip command as follows:

    [user@RHEL_77_server rapid7]$ sudo pip install --upgrade git+https://github.com/rapid7/vm-console-client-python.git
 
Proof:    whereas before in the directory  /lib/python2.7/site-packages/ only this single .egg-info file was present:

    drwxr-xr-x 2 root  root           105 Jan 31 14:27 rapid7_vm_console.egg-info

after running the PIP upgrade command,  the directory  /lib/python2.7/site-packages/   now contains the following three files:

    drwxr-xr-x    4 root root   4096 Feb  3 13:35 rapid7vmconsole
    -rw-r--r--    1 root root  11511 Jan 31 09:18 rapid7_vm_console-1.0.0_6.5.50-py2.7.egg
    drwxr-xr-x    2 root root    131 Feb  3 13:35 rapid7_vm_console-1.0.0_6.5.50-py2.7.egg-info

The module can now be successfully imported into scripts.  Hope this helps others, thanks.
