### ISSUE TITLE
ValueError: Invalid value for `name`, must not be `None` , for administration/info

### ISSUE THREAD

**Issue by TheRaj390** [rapid7/vm-console-client-python#30]
## Issues
When performing a request towards `/administration/info` I get a ValueError: Invalid value for `name`, must not be `None`  error. This error does not appear when performing other requests like `/administration/license`

### Actual Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api\administration_api.py", line 247, in get_info
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api\administration_api.py", line 304, in get_info_with_http_info
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 315, in call_api
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 159, in __call_api
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 231, in deserialize
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 270, in __deserialize
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 611, in __deserialize_model
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 270, in __deserialize
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 611, in __deserialize_model
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 270, in __deserialize
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 611, in __deserialize_model
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 270, in __deserialize
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\api_client.py", line 613, in __deserialize_model
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\models\file.py", line 58, in __init__
  File "C:\Users\TheRaj390\AppData\Roaming\Python\Python38\site-packages\rapid7_vm_console-1.0.0_6.5.50-py3.8.egg\rapid7vmconsole\models\file.py", line 107, in name
ValueError: Invalid value for `name`, must not be `None`
```

### Steps to Reproduce (for bugs)

Python code that reproduces the issue:
```python
from __future__ import print_function
import time
import base64
import rapid7vmconsole
from rapid7vmconsole.rest import ApiException
from pprint import pprint

config = rapid7vmconsole.Configuration(name='Rapid7')
config.username = 'username'
config.password = 'password'
config.host = 'ip:port'
config.verify_ssl = False
config.assert_hostname = False
config.proxy = None
config.ssl_ca_cert = None
config.connection_pool_maxsize = None
config.cert_file = None
config.key_file = None
config.safe_chars_for_path_param = ''

auth = "%s:%s" % (config.username, config.password)
auth = base64.b64encode(auth.encode('ascii')).decode()
client = rapid7vmconsole.ApiClient(configuration=config)
client.default_headers['Authorization'] = "Basic %s" % auth

api_instance = rapid7vmconsole.AdministrationApi(client)

try:
    api_response = api_instance.get_info()
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AdministrationApi->get_info: %s\n" % e)
```

### Your Environment
* Python version: 3.8.1
* Operating System and version: Windows 10 v1909
* InsightVM/Nexpose product version: InsightVM 6.6.11

**Comment by TheRaj390** [comment]
Issue resolved itself in version 6.6.10.
Thanks!
