### ISSUE TITLE
scan_api.start_scan is broken and example does not work

### ISSUE THREAD

**Issue by dsielert** [rapid7/vm-console-client-python#34]
## Issues and Contributing
calling start_scan per example doc produces error

### Expected Behavior
Scan would be started and receive a 200 response 
### Actual Behavior
```
rapid7vmconsole.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store, must-revalidate', 'Content-Type': 'application/json;charset=utf-8', 'Date': 'Fri, 05 Jun 2020 14:09:30 GMT', 'Server': 'Security Console', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-UA-Compatible': 'IE=edge,chrome=1', 'X-XSS-Protection': '1; mode=block', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive'})
HTTP response body: {
  "status" : 400,
  "message" : "An unexpected error occurred. See the log file for more information or contact support.",
  "links" : [ {
    "href" : "https://rapid7.xxxxxx.com/api/3/sites/2/scans",
    "rel" : "self"
  } ]
}
```

### Steps to Reproduce (for bugs)
use the one from the example doc on start_sscan

### Your Environment
* Library version or repository branch: master
* Python version: 3.8
* Operating System and version: macos
* InsightVM/Nexpose product version:

**Comment by zez3** [comment]
Same here, 
I suspect that that the update with the TLS 1.2 only broke the compatibility

on the server side I get:
eg:

```
2021-11-09T09:37:20 [WARN] [Thread: http-nio-443-exec-77=/api/3/tags] An unhandled exception has been detected.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.nexposeDataSource' defined in class com.rapid7.nexpose.nsc.web.config.DatabaseConfig: Bean instantiation via factory method failed; nested exception i
s org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'nexposeDataSource' threw exception; nested exception is java.lang.NullPointerException
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'nexposeDataSource' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        ... 163 common frames omitted
Caused by: java.lang.NullPointerException: null

```

**Comment by zez3** [comment]
Actually, scratch that. It works, I forgot the headers
`client.default_headers['Authorization'] = "Basic %s" % auth`
