### ISSUE TITLE
New Vulnerability Investigation gives an Exception in userapi.get_users method

### ISSUE THREAD

**Issue by PNO2020** [rapid7/vm-console-client-python#38]
When getting the users from the InsightVM by using the method userapi.get_users an exception is raised.
This due to the new functionality in InsightVM, cq. Vulnerability Investigation.
There are now more 'privileges' returned than the API expects.

Output of a simple python script:

Traceback (most recent call last):
  File [HIDDEN], line 42, in get_users
    result = userapi.get_users(page=page)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api/user_api.py", line 1825, in get_users
    (data) = self.get_users_with_http_info(**kwargs)  # noqa: E501
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api/user_api.py", line 1906, in get_users_with_http_info
    collection_formats=collection_formats)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 328, in call_api
    _preload_content, _request_timeout)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 167, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 239, in deserialize
    return self.__deserialize(data, response_type)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 622, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 256, in __deserialize
    for sub_data in data]
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 256, in <listcomp>
    for sub_data in data]
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 622, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/api_client.py", line 624, in __deserialize_model
    instance = klass(**kwargs)
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/models/user_role.py", line 69, in __init__
    self.privileges = privileges
  File "/var/insightvm/vm-console-client-python-master/rapid7vmconsole/models/user_role.py", line 190, in privileges
    ", ".join(map(str, allowed_values)))

ValueError: Invalid values for `privileges` [manage-vuln-investigations, view-vuln-investigations], must be a subset of [all-permissions, create-reports, configure-global-settings, manage-sites, manage-tags, manage-static-asset-groups, manage-dynamic-asset-groups, manage-scan-templates, manage-report-templates, manage-scan-engines, submit-vulnerability-exceptions, approve-vulnerability-exceptions, delete-vulnerability-exceptions, create-tickets, close-tickets, assign-ticket-assignee, manage-site-access, manage-asset-group-access, manage-report-access, use-restricted-report-sections, manage-policies, view-asset-group-asset-data, manage-asset-group-assets, view-site-asset-data, specify-site-metadata, purge-site-asset-data, specify-scan-targets, assign-scan-engine, assign-scan-template, manage-site-credentials, manage-scan-alerts, schedule-automatic-scans, start-unscheduled-scans]

Solution: 
No Possible Solution except changing the API

Environment
Unix
Python3

**Comment by kiblik** [comment]
I suppose https://github.com/rapid7/vm-console-client-python/pull/37 fix your issues

**Comment by PNO2020** [comment]
Tnx Kiblik for the solution.
Implemented it and seems to work fine.

Would be nice that this - and other - solutions could be merged into a new stable version.

**Comment by zyoutz-r7** [comment]
Latest release for InsightVM console 6.6.55 has been released and client generated.  This includes the newest privileges for manage and view vuln investigations
