### ISSUE TITLE
Unable to use get_assets if an asset contains a configuration value of {}.

### ISSUE THREAD

**Issue by alee-r7** [rapid7/vm-console-client-python#48]
## Issues and Contributing

Discovered this issue where we had an asset and the asset had configurations (not the asset service's configuration). One of the configurations on the asset has "{}" as the value.

This caused an issue in the client during deseriliazation. Here is the stack trace.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/DivvyUtils/decorators.py", line 40, in decorator_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/DivvyBlueprints/v2/__init__.py", line 404, in decorator_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/DivvyPermissions/decorators.py", line 313, in wrapper_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/DivvyUtils/decorators.py", line 40, in decorator_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/DivvyPermissions/decorators.py", line 367, in wrapper_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/DivvyBlueprints/v2/prototype/v2_integrations.py", line 275, in set_integration_settings
    test_ivm_settings(organization)
  File "/usr/local/lib/python3.8/dist-packages/DivvyBotfactory/integrations/insightvm.py", line 103, in test_ivm_settings
    asset_api.get_assets(page=0, size=10, _request_timeout=5)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api/asset_api.py", line 2081, in get_assets
    (data) = self.get_assets_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api/asset_api.py", line 2148, in get_assets_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 323, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 167, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 239, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 622, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 255, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 255, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 622, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 255, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 255, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 622, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 255, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 255, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 278, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/api_client.py", line 624, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/models/configuration.py", line 48, in __init__
    self.name = name
  File "/usr/local/lib/python3.8/dist-packages/rapid7vmconsole/models/configuration.py", line 73, in name
    raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
```

and below is a sample of the asset with this as its configuration.

```
"configurations": [
        {
          "name": "attributes",
          "value": "Test"
        },
        {
          "name": "cpuinfo",
          "value": "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz"
        },
        {
          "name": "proxies",
          "value": "{}"
        },
        {
          "name": "release",
          "value": "10"
        },
        {
          "name": "timezone",
          "value": "GMT-4"
        }
``` 

When you call get_asset and if the response returns this asset with this configuration, the api call fails and the above stack trace is shown.

**Comment by MazerRackham** [comment]
We are experiencing the same issue in our environment.
